version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: graphql_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: graph
    ports:
      - "5431:5432" # Host port 5431 mapped to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql_server
    restart: always
    environment:
      PORT: 4000
      DATABASE_URL: "postgresql://postgres:root@postgres:5432/graph" # Updated to use Docker network
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
